version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
  frontend:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    environment:
      - API_URL=http://backend:8000/api